export const INTRO_INDEX = 7;
export const SECTION_SPACING = 92;
export const NASA_TEXTURES = {
  earthHigh: 'https://svs.gsfc.nasa.gov/vis/a000000/a003600/a003615/flat_earth_Largest_still.0330.jpg',
  earthLow: 'https://svs.gsfc.nasa.gov/vis/a000000/a003600/a003615/flat_earth03.jpg',
  earthNight: 'https://svs.gsfc.nasa.gov/vis/a000000/a002900/a002916/earthatnight-2048.png',
};
export const SCALE_SECTIONS = [
{id:'type-6',label:'Type VI',shortLabel:'VI',group:'Speculative extension',realm:'speculative',accent:'#f1dcff',scaleLabel:'Designed realities',classification:'Speculative extension',comparison:'Geometry, causality, and the conditions of cosmic birth become engineering materials.',scene:'reality',camera:{fov:54,roll:-.06,drift:1.4}},
{id:'type-5',label:'Type V',shortLabel:'V',group:'Speculative extension',realm:'speculative',accent:'#d7b8ff',scaleLabel:'Universe foundries',classification:'Speculative extension',comparison:'Entire universes become potential habitats, laboratories, archives, and machines.',scene:'multiverse',camera:{fov:50,roll:.04,drift:1.1}},
{id:'type-4',label:'Type IV',shortLabel:'IV',group:'Speculative extension',realm:'speculative',accent:'#aeb5ff',scaleLabel:'The observable universe',classification:'Speculative extension',comparison:'Galaxy clusters and the cosmic web become one distributed civilization-scale system.',scene:'cosmic-web',camera:{fov:52,roll:-.025,drift:1.3}},
{id:'type-3',label:'Type III',shortLabel:'III',group:'Original Kardashev scale',realm:'macro',accent:'#9dbdff',scaleLabel:'A galaxy',classification:'Original Kardashev scale',comparison:'Billions of stellar systems become linked centers of life, industry, and computation.',scene:'galaxy',camera:{fov:47,roll:.015,drift:1.15}},
{id:'type-2',label:'Type II',shortLabel:'II',group:'Original Kardashev scale',realm:'macro',accent:'#ffd59a',scaleLabel:'A star',classification:'Original Kardashev scale',comparison:'A solar system becomes an engineered habitat powered by a meaningful share of its star.',scene:'dyson',camera:{fov:45,roll:-.01,drift:.8}},
{id:'type-1',label:'Type I',shortLabel:'I',group:'Original Kardashev scale',realm:'macro',accent:'#8df4d4',scaleLabel:'A planet',classification:'Original Kardashev scale',comparison:'The energy flowing through an entire world becomes reliable civilization infrastructure.',scene:'planetary',camera:{fov:42,roll:.006,drift:.65}},
{id:'type-0',label:'Type 0',shortLabel:'0',group:'Later extension',realm:'macro',accent:'#79d7ff',scaleLabel:'A connected world',classification:'Later extension',comparison:'A planetary nervous system emerges before the civilization can fully control planetary energy.',scene:'connected-earth',camera:{fov:42,roll:-.004,drift:.55}},
{id:'introduction',label:'Present',shortLabel:'NOW',group:'You are here',realm:'present',accent:'#d7b6ff',scaleLabel:'The point of departure',classification:'Two directions of mastery',comparison:'Travel outward through energy scales or inward through the structure of matter itself.',scene:'present',camera:{fov:44,roll:0,drift:.5}},
{id:'type-i-minus',label:'Type I−',shortLabel:'I−',group:'Barrow scale',realm:'micro',accent:'#ffbd8d',scaleLabel:'Human-scale matter',classification:'Barrow microdimensional scale',comparison:'Landscapes, structures, machines, and materials can be reshaped at macroscopic scales.',scene:'material',camera:{fov:48,roll:.02,drift:.8}},
{id:'type-ii-minus',label:'Type II−',shortLabel:'II−',group:'Barrow scale',realm:'micro',accent:'#ff8ebf',scaleLabel:'Living systems',classification:'Barrow microdimensional scale',comparison:'Genetic information and biological development become readable and programmable.',scene:'biology',camera:{fov:50,roll:-.025,drift:.9}},
{id:'type-iii-minus',label:'Type III−',shortLabel:'III−',group:'Barrow scale',realm:'micro',accent:'#e18cff',scaleLabel:'Molecules and bonds',classification:'Barrow microdimensional scale',comparison:'Matter can be designed by controlling how atoms connect and how reactions unfold.',scene:'molecular',camera:{fov:48,roll:.035,drift:1.05}},
{id:'type-iv-minus',label:'Type IV−',shortLabel:'IV−',group:'Barrow scale',realm:'micro',accent:'#92a8ff',scaleLabel:'Individual atoms',classification:'Barrow microdimensional scale',comparison:'Atomically precise manufacturing can remove defects and build matter from the bottom upward.',scene:'atomic',camera:{fov:46,roll:-.03,drift:1.1}},
{id:'type-v-minus',label:'Type V−',shortLabel:'V−',group:'Barrow scale',realm:'micro',accent:'#73e2ff',scaleLabel:'Atomic nuclei',classification:'Barrow microdimensional scale',comparison:'Elements, isotopes, fusion, fission, and nuclear states become deliberate manufacturing choices.',scene:'nuclear',camera:{fov:45,roll:.02,drift:1}},
{id:'type-vi-minus',label:'Type VI−',shortLabel:'VI−',group:'Barrow scale',realm:'micro',accent:'#8fffe4',scaleLabel:'Elementary particles',classification:'Barrow microdimensional scale',comparison:'Quarks, leptons, fields, and matter-energy conversion become potential fabrication tools.',scene:'particle',camera:{fov:52,roll:-.02,drift:1.25}},
{id:'type-omega-minus',label:'Type Ω−',shortLabel:'Ω−',group:'Speculative Barrow endpoint',realm:'micro',accent:'#ffffff',scaleLabel:'Spacetime itself',classification:'Speculative Barrow endpoint',comparison:'The geometry and quantum structure of spacetime become the final proposed engineering frontier.',scene:'spacetime',camera:{fov:56,roll:.05,drift:1.5}},
];
export function clampProgress(value){return Math.max(0,Math.min(SCALE_SECTIONS.length-1,value));}
export function getSectionIndexFromLocation(){const params=new URLSearchParams(window.location.search);const requested=Number.parseFloat(params.get('page')||'');if(Number.isFinite(requested))return clampProgress(requested);const hash=window.location.hash.replace(/^#/,'');const index=SCALE_SECTIONS.findIndex((section)=>section.id===hash);if(index>=0)return index;const saved=Number.parseFloat(window.sessionStorage.getItem('kardashev-progress')||'');return Number.isFinite(saved)?clampProgress(saved):INTRO_INDEX;}
